-- ============================================================================
--  TECHZONE - Script unificado de base de datos para MySQL 8.0 / MariaDB 10.5+
--  Uso: pegar y ejecutar completo en MySQL Workbench / phpMyAdmin / DBeaver
--  Archivo: base de datos  proyecto  |  Charset: utf8mb4  |  Motor: InnoDB
--
--  Modelo de venta:
--    venta.id_cliente -> COMPRADOR   (tabla cliente)
--    venta.id_persona -> VENDEDOR    (tabla persona, usuario que proceso la venta)
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Crear la base de datos (no se borra si ya existe)
CREATE DATABASE IF NOT EXISTS proyecto
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE proyecto;

-- 2. Limpieza previa (MySQL no admite "CASCADE" en DROP TABLE ni multiples tablas)
DROP VIEW  IF EXISTS historial_compras;
DROP TABLE IF EXISTS detalle_venta;
DROP TABLE IF EXISTS venta;
DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS persona;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS medio_pago;
DROP TABLE IF EXISTS tipo_documento;

-- ============================================================================
--  ESTRUCTURA
-- ============================================================================

-- Parametros del sistema (IGV, RUC emisor, etc). Editables sin tocar el codigo.
CREATE TABLE parametro (
    id_parametro VARCHAR(30)  NOT NULL,
    valor        VARCHAR(50)  NOT NULL,
    descripcion  VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_parametro)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tipo_documento (
    id_documento VARCHAR(25)  NOT NULL,
    nombre      VARCHAR(50)  NOT NULL,
    PRIMARY KEY (id_documento)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medio_pago (
    id_medio_pago VARCHAR(10)  NOT NULL,
    descripcion   VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_medio_pago)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE persona (
    id_persona       VARCHAR(25) NOT NULL,
    nombre           VARCHAR(50) NOT NULL,
    apellido         VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE,
    correo           VARCHAR(100),
    telefono         VARCHAR(9),
    usuario          VARCHAR(50),
    PRIMARY KEY (id_persona)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- id_usuario: GENERATED BY DEFAULT AS IDENTITY (Postgres) -> AUTO_INCREMENT (MySQL)
CREATE TABLE usuario (
    id_usuario INT          NOT NULL AUTO_INCREMENT,
    usuario    VARCHAR(50)  NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    id_persona VARCHAR(25)  NOT NULL,
    PRIMARY KEY (id_usuario),
    KEY idx_usuario_id_persona (id_persona),
    CONSTRAINT fk_usuario_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- El COMPRADOR. Antes de esta version la tabla no tenia ninguna relacion:
-- se relacionaba con persona() a traves de venta.id_persona.
CREATE TABLE cliente (
    id_cliente VARCHAR(20)  NOT NULL,
    nombre     VARCHAR(50)  NOT NULL,
    apellido   VARCHAR(50)  NOT NULL,
    telefono   VARCHAR(15),
    contrasena VARCHAR(255) NOT NULL,
    correo     VARCHAR(100),
    UNIQUE KEY uk_cliente_correo (correo),
    PRIMARY KEY (id_cliente)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE producto (
    id_producto INT            NOT NULL,
    nombre      VARCHAR(100)   NOT NULL,
    stock       INT            NOT NULL,
    precio      DECIMAL(10, 2) NOT NULL,
    categoria   VARCHAR(80)    NOT NULL,
    PRIMARY KEY (id_producto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- id_cliente = comprador  |  id_persona = vendedor/empleado que proceso la venta
CREATE TABLE venta (
    id_venta          VARCHAR(36) NOT NULL,
    id_cliente        VARCHAR(20) NOT NULL,
    id_persona        VARCHAR(25) NOT NULL,
    id_tipo_documento VARCHAR(25) NOT NULL,
    numero_documento  VARCHAR(36) NOT NULL,
    id_medio_pago     VARCHAR(10) NOT NULL,
    fecha_emision     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_venta),
    KEY idx_venta_id_cliente (id_cliente),
    KEY idx_venta_id_persona (id_persona),
    KEY idx_venta_id_tipo_documento (id_tipo_documento),
    KEY idx_venta_id_medio_pago (id_medio_pago),
    KEY idx_venta_fecha_emision (fecha_emision),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente (id_cliente),
    CONSTRAINT fk_venta_persona FOREIGN KEY (id_persona)
        REFERENCES persona (id_persona),
    CONSTRAINT fk_venta_tipo_documento FOREIGN KEY (id_tipo_documento)
        REFERENCES tipo_documento (id_documento),
    CONSTRAINT fk_venta_medio_pago FOREIGN KEY (id_medio_pago)
        REFERENCES medio_pago (id_medio_pago)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- id_detalle: GENERATED BY DEFAULT AS IDENTITY (Postgres) -> AUTO_INCREMENT (MySQL)
CREATE TABLE detalle_venta (
    id_detalle      INT            NOT NULL AUTO_INCREMENT,
    id_venta        VARCHAR(36)    NOT NULL,
    id_producto     INT            NOT NULL,
    cantidad        INT            NOT NULL,
    precio_unitario DECIMAL(10, 2) NOT NULL,
    subtotal        DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id_detalle),
    KEY idx_detalle_id_venta (id_venta),
    KEY idx_detalle_id_producto (id_producto),
    CONSTRAINT fk_detalle_venta FOREIGN KEY (id_venta)
        REFERENCES venta (id_venta),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto)
        REFERENCES producto (id_producto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
--  DATOS INICIALES
-- ============================================================================

INSERT INTO parametro (id_parametro, valor, descripcion) VALUES
('IGV_PORCENTAJE', '18.00', 'Impuesto General a las Ventas (IGV) en porcentaje, Peru'),
('RUC_EMISOR', '20512345678', 'RUC del emisor para los comprobantes'),
('MONEDA', 'PEN', 'Codigo de moneda ISO 4217');

INSERT INTO tipo_documento VALUES
('TD001', 'Boleta'),
('TD002', 'Factura');

INSERT INTO medio_pago VALUES
('MP001', 'Efectivo'),
('MP002', 'Tarjeta de crédito'),
('MP003', 'Tarjeta de débito'),
('MP004', 'Yape'),
('MP005', 'Plin'),
('MP006', 'Transferencia'),
('MP007', 'Pago contra entrega'),
('MP008', 'Billetera digital'),
('MP009', 'Visa'),
('MP010', 'Mastercard'),
('MP011', 'American Express'),
('MP012', 'Depósito'),
('MP013', 'Crédito empresarial'),
('MP014', 'Pago mixto'),
('MP015', 'PayPal');

INSERT INTO persona VALUES
('PER001', 'Luis', 'García', '1998-05-12', 'luis@gmail.com', '987654321', 'luisg'),
('PER002', 'Ana', 'Torres', '1999-08-20', 'ana@gmail.com', '987654322', 'anat'),
('PER003', 'Carlos', 'Ramos', '1997-03-15', 'carlos@gmail.com', '987654323', 'carlosr'),
('PER004', 'María', 'Flores', '2000-11-10', 'maria@gmail.com', '987654324', 'mariaf'),
('PER005', 'Pedro', 'Castro', '1996-01-25', 'pedro@gmail.com', '987654325', 'pedroc'),
('PER006', 'Lucía', 'Mendoza', '2001-06-30', 'lucia@gmail.com', '987654326', 'luciam'),
('PER007', 'Jorge', 'Paredes', '1995-09-18', 'jorge@gmail.com', '987654327', 'jorgep'),
('PER008', 'Rosa', 'Vargas', '1998-12-05', 'rosa@gmail.com', '987654328', 'rosav'),
('PER009', 'Miguel', 'Salas', '1994-04-22', 'miguel@gmail.com', '987654329', 'miguels'),
('PER010', 'Diana', 'Quispe', '2002-02-14', 'diana@gmail.com', '987654330', 'dianaq'),
('PER011', 'José', 'Reyes', '1999-07-07', 'jose@gmail.com', '987654331', 'joser'),
('PER012', 'Elena', 'Campos', '1997-10-09', 'elena@gmail.com', '987654332', 'elenac'),
('PER013', 'Raúl', 'Navarro', '1996-03-29', 'raul@gmail.com', '987654333', 'rauln'),
('PER014', 'Sofía', 'Herrera', '2001-05-19', 'sofia@gmail.com', '987654334', 'sofiah'),
('PER015', 'Fernando', 'Lozano', '1995-08-11', 'fernando@gmail.com', '987654335', 'fernandol'),
('PERADM', 'Administrador', 'General', '1995-01-01', 'admin@softplex.com', '999999999', 'admin');

INSERT INTO usuario (usuario, contrasena, id_persona) VALUES
('luisg', '123456', 'PER001'),
('anat', '123456', 'PER002'),
('carlosr', '123456', 'PER003'),
('mariaf', '123456', 'PER004'),
('pedroc', '123456', 'PER005'),
('luciam', '123456', 'PER006'),
('jorgep', '123456', 'PER007'),
('rosav', '123456', 'PER008'),
('miguels', '123456', 'PER009'),
('dianaq', '123456', 'PER010'),
('joser', '123456', 'PER011'),
('elenac', '123456', 'PER012'),
('rauln', '123456', 'PER013'),
('sofiah', '123456', 'PER014'),
('fernandol', '123456', 'PER015'),
('admin', '123456', 'PERADM');

INSERT INTO cliente VALUES
('CLI001', 'Luis', 'García', '987654321', '123456', 'luis@gmail.com'),
('CLI002', 'Ana', 'Torres', '987654322', '123456', 'ana@gmail.com'),
('CLI003', 'Carlos', 'Ramos', '987654323', '123456', 'carlos@gmail.com'),
('CLI004', 'María', 'Flores', '987654324', '123456', 'maria@gmail.com'),
('CLI005', 'Pedro', 'Castro', '987654325', '123456', 'pedro@gmail.com'),
('CLI006', 'Lucía', 'Mendoza', '987654326', '123456', 'lucia@gmail.com'),
('CLI007', 'Jorge', 'Paredes', '987654327', '123456', 'jorge@gmail.com'),
('CLI008', 'Rosa', 'Vargas', '987654328', '123456', 'rosa@gmail.com'),
('CLI009', 'Miguel', 'Salas', '987654329', '123456', 'miguel@gmail.com'),
('CLI010', 'Diana', 'Quispe', '987654330', '123456', 'diana@gmail.com'),
('CLI011', 'José', 'Reyes', '987654331', '123456', 'jose@gmail.com'),
('CLI012', 'Elena', 'Campos', '987654332', '123456', 'elena@gmail.com'),
('CLI013', 'Raúl', 'Navarro', '987654333', '123456', 'raul@gmail.com'),
('CLI014', 'Sofía', 'Herrera', '987654334', '123456', 'sofia@gmail.com'),
('CLI015', 'Fernando', 'Lozano', '987654335', '123456', 'fernando@gmail.com');

INSERT INTO producto VALUES
(1, 'Laptop Lenovo', 20, 2500.00, 'Laptops'),
(2, 'Mouse Logitech', 50, 45.00, 'Periféricos'),
(3, 'Teclado Mecánico', 35, 150.00, 'Periféricos'),
(4, 'Monitor Samsung', 18, 780.00, 'Monitores'),
(5, 'Impresora Epson', 12, 650.00, 'Impresión'),
(6, 'USB 32GB', 100, 25.00, 'Almacenamiento'),
(7, 'Disco SSD 480GB', 40, 230.00, 'Almacenamiento'),
(8, 'Audífonos Sony', 30, 120.00, 'Audio'),
(9, 'Parlante JBL', 25, 180.00, 'Audio'),
(10, 'Tablet Samsung', 15, 950.00, 'Tablets'),
(11, 'Cámara Web', 22, 90.00, 'Accesorios'),
(12, 'Router TP-Link', 28, 160.00, 'Redes'),
(13, 'Cable HDMI', 60, 30.00, 'Cables'),
(14, 'Silla Gamer', 10, 520.00, 'Gaming'),
(15, 'Micrófono USB', 17, 210.00, 'Audio');

-- Comprador en id_cliente (CLI001..CLI015). Vendedor en id_persona (PERADM,
-- el administrador que registro la carga inicial).
INSERT INTO venta (id_venta, id_cliente, id_persona, id_tipo_documento, numero_documento, id_medio_pago, fecha_emision) VALUES
('VEN001', 'CLI001', 'PERADM', 'TD001', 'B001-000001', 'MP004', CURRENT_TIMESTAMP),
('VEN002', 'CLI002', 'PERADM', 'TD002', 'F001-000002', 'MP002', CURRENT_TIMESTAMP),
('VEN003', 'CLI003', 'PERADM', 'TD001', 'B001-000003', 'MP001', CURRENT_TIMESTAMP),
('VEN004', 'CLI004', 'PERADM', 'TD002', 'F001-000004', 'MP006', CURRENT_TIMESTAMP),
('VEN005', 'CLI005', 'PERADM', 'TD001', 'B001-000005', 'MP005', CURRENT_TIMESTAMP),
('VEN006', 'CLI006', 'PERADM', 'TD002', 'F001-000006', 'MP009', CURRENT_TIMESTAMP),
('VEN007', 'CLI007', 'PERADM', 'TD001', 'B001-000007', 'MP003', CURRENT_TIMESTAMP),
('VEN008', 'CLI008', 'PERADM', 'TD002', 'F001-000008', 'MP010', CURRENT_TIMESTAMP),
('VEN009', 'CLI009', 'PERADM', 'TD001', 'B001-000009', 'MP001', CURRENT_TIMESTAMP),
('VEN010', 'CLI010', 'PERADM', 'TD002', 'F001-000010', 'MP004', CURRENT_TIMESTAMP),
('VEN011', 'CLI011', 'PERADM', 'TD001', 'B001-000011', 'MP005', CURRENT_TIMESTAMP),
('VEN012', 'CLI012', 'PERADM', 'TD002', 'F001-000012', 'MP006', CURRENT_TIMESTAMP),
('VEN013', 'CLI013', 'PERADM', 'TD001', 'B001-000013', 'MP007', CURRENT_TIMESTAMP),
('VEN014', 'CLI014', 'PERADM', 'TD002', 'F001-000014', 'MP013', CURRENT_TIMESTAMP),
('VEN015', 'CLI015', 'PERADM', 'TD001', 'B001-000015', 'MP015', CURRENT_TIMESTAMP);

INSERT INTO detalle_venta (id_venta, id_producto, cantidad, precio_unitario, subtotal) VALUES
('VEN001', 1, 1, 2500.00, 2500.00),
('VEN001', 2, 2, 45.00, 90.00),
('VEN002', 4, 1, 780.00, 780.00),
('VEN002', 3, 1, 150.00, 150.00),
('VEN003', 6, 3, 25.00, 75.00),
('VEN004', 5, 1, 650.00, 650.00),
('VEN005', 7, 1, 230.00, 230.00),
('VEN006', 8, 2, 120.00, 240.00),
('VEN007', 9, 1, 180.00, 180.00),
('VEN008', 10, 1, 950.00, 950.00),
('VEN009', 11, 2, 90.00, 180.00),
('VEN010', 12, 1, 160.00, 160.00),
('VEN011', 13, 4, 30.00, 120.00),
('VEN012', 14, 1, 520.00, 520.00),
('VEN013', 15, 1, 210.00, 210.00),
('VEN014', 1, 1, 2500.00, 2500.00),
('VEN015', 2, 1, 45.00, 45.00);

-- ============================================================================
--  VISTA
--  "cliente" y "apellido" provienen ahora de la tabla cliente (el comprador).
--  "vendedor" se sigue obteniendo de persona a traves de venta.id_persona.
-- ============================================================================

CREATE OR REPLACE VIEW historial_compras AS
SELECT
    v.id_venta,
    v.fecha_emision,
    td.nombre AS tipo_documento,
    cl.nombre AS cliente,
    cl.apellido,
    pr.nombre AS producto,
    dv.cantidad,
    dv.precio_unitario,
    dv.subtotal,
    mp.descripcion AS medio_pago,
    pe.nombre AS vendedor
FROM venta v
INNER JOIN cliente cl       ON v.id_cliente = cl.id_cliente
INNER JOIN persona pe       ON v.id_persona = pe.id_persona
INNER JOIN tipo_documento td ON v.id_tipo_documento = td.id_documento
INNER JOIN medio_pago mp    ON v.id_medio_pago = mp.id_medio_pago
INNER JOIN detalle_venta dv ON v.id_venta = dv.id_venta
INNER JOIN producto pr      ON dv.id_producto = pr.id_producto;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================================
--  VERIFICACION (opcional)
--  Debe devolver 2, 15, 16, 16, 15, 15, 15, 17, 17
--  SELECT 'tipo_documento' AS tabla, COUNT(*) AS filas FROM tipo_documento
--  UNION ALL SELECT 'medio_pago', COUNT(*) FROM medio_pago
--  UNION ALL SELECT 'persona', COUNT(*) FROM persona
--  UNION ALL SELECT 'usuario', COUNT(*) FROM usuario
--  UNION ALL SELECT 'cliente', COUNT(*) FROM cliente
--  UNION ALL SELECT 'producto', COUNT(*) FROM producto
--  UNION ALL SELECT 'venta', COUNT(*) FROM venta
--  UNION ALL SELECT 'detalle_venta', COUNT(*) FROM detalle_venta
--  UNION ALL SELECT 'historial_compras', COUNT(*) FROM historial_compras;
--
--  Comprobar que cliente quedo relacionado:
--  SELECT v.id_venta, cl.nombre, cl.apellido, pe.nombre AS vendedor
--  FROM venta v
--  INNER JOIN cliente cl ON v.id_cliente = cl.id_cliente
--  INNER JOIN persona pe ON v.id_persona = pe.id_persona
--  LIMIT 3;
-- ============================================================================
