DROP VIEW IF EXISTS historial_compras;
DROP TABLE IF EXISTS detalle_venta, venta, usuario, persona, cliente, producto, tipo_documento, medio_pago CASCADE;

CREATE TABLE tipo_documento (
    id_documento VARCHAR(25) PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL
);

CREATE TABLE medio_pago (
    id_medio_pago VARCHAR(10) PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL
);

CREATE TABLE persona (
    id_persona VARCHAR(25) PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE,
    correo VARCHAR(100),
    telefono VARCHAR(9),
    usuario VARCHAR(50)
);

CREATE TABLE usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    id_persona VARCHAR(25) NOT NULL,
    FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
);

CREATE TABLE cliente (
    id_cliente VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    telefono VARCHAR(15),
    contrasena VARCHAR(255) NOT NULL,
    correo VARCHAR(100) UNIQUE
);

CREATE TABLE producto (
    id_producto INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    stock INTEGER NOT NULL,
    precio NUMERIC(10,2) NOT NULL,
    categoria VARCHAR(50) NOT NULL
);

CREATE TABLE venta (
    id_venta VARCHAR(36) PRIMARY KEY,
    id_persona VARCHAR(25) NOT NULL,
    id_tipo_documento VARCHAR(25) NOT NULL,
    numero_documento VARCHAR(36) NOT NULL,
    id_medio_pago VARCHAR(10) NOT NULL,
    fecha_emision TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_persona) REFERENCES persona(id_persona),
    FOREIGN KEY (id_tipo_documento) REFERENCES tipo_documento(id_documento),
    FOREIGN KEY (id_medio_pago) REFERENCES medio_pago(id_medio_pago)
);

CREATE TABLE detalle_venta (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta VARCHAR(36) NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (id_venta) REFERENCES venta(id_venta),
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);
